version: '3.5'

volumes:
  zookeeper_data: ~
  kafka_data: ~

services:
  zookeeper:
    image: bitnami/zookeeper
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  cmak:
    build:
      context: docker/cmak
    environment:
      ZK_HOSTS: "zookeeper:2181"
    ports:
      - '${CMAK_PORT}:9000'
